# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY tsconfig.json .
COPY src ./src

# Build the project
RUN npm run build

# Expose stdio via CMD
CMD ["node", "dist/index.js"]
